// <auto-generated />
using System;
using LoanAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_U2_POO_CarlosPineda.Migrations
{
    [DbContext(typeof(ExamenU2Context))]
    partial class ExamenU2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanAPI.Database.Entities.AmortizationScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("days");

                    b.Property<decimal>("ExtraordinaryPayment")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("extraordinary_payment");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("interest");

                    b.Property<decimal>("LevelPaymentWithSVSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("level_payment_with_svds");

                    b.Property<decimal>("LevelPaymentWithoutSVSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("level_payment_without_svds");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<decimal>("OtherChargesSVSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("other_charges_svds");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("principal");

                    b.Property<decimal>("PrincipalBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("principal_balance");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("amortization_schedule", "dbo");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("identity_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("customers", "dbo");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.LoanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("disbursement_date");

                    b.Property<DateTime>("FirstPaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_payment_date");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("interest_rate");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("loan_amount");

                    b.Property<int>("Term")
                        .HasColumnType("int")
                        .HasColumnName("term");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("loans", "dbo");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.AmortizationScheduleEntity", b =>
                {
                    b.HasOne("LoanAPI.Database.Entities.LoanEntity", "Loan")
                        .WithMany("AmortizationSchedule")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.LoanEntity", b =>
                {
                    b.HasOne("LoanAPI.Database.Entities.CustomerEntity", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LoanAPI.Database.Entities.LoanEntity", b =>
                {
                    b.Navigation("AmortizationSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
